# Basic Analysis of the data

In [1]:
#Importing require libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error

In [2]:
#Loading data
data = pd.read_csv('C:\\Users\\bhavi\\OneDrive\\Desktop\\Data\\bangalore house price prediction OHE-data.csv')

In [3]:
#View the data
data.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [4]:
#Checking missing values in the data
data.isnull().sum().sum()

0

# Splitting data into X & y and
# Splitting X & y into train and test

In [5]:
#Splitting data into X & y
X = data.drop(columns='price', axis = 1)
y = data['price']
print('X shape = ',X.shape)
print('y shape = ',y.shape)

X shape =  (7120, 107)
y shape =  (7120,)


In [6]:
#Splitting data into trainn and test
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 51)
print('X_train shape =', X_train.shape)
print('X_test shape =', X_test.shape)
print('y_train shape =', y_train.shape)
print('y_test shape =', y_test.shape)

X_train shape = (5696, 107)
X_test shape = (1424, 107)
y_train shape = (5696,)
y_test shape = (1424,)


# Feature Scaling of train and test data

In [7]:
#Feature scaling on X_train and X_test
sc = StandardScaler()
sc.fit(X_train, X_test)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

In [8]:
#Checking X_train after feature scaling
X_train

array([[ 3.0245515 ,  0.55008644,  1.33396246, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -2.0427027 , -0.60737352, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.36873754, ..., -0.05630391,
        -0.05630391, -0.05138463],
       ...,
       [-0.44274597,  0.55008644, -0.49772996, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.62414253, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -0.74630813, -0.6009239 , ..., -0.05630391,
        -0.05630391, -0.05138463]])

In [9]:
#Checking X_test after feature scaling
X_test

array([[ 0.71301986,  0.0112734 ,  0.30202307, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597,  0.55008644, -0.58028511, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [ 1.86878568,  0.55008644,  0.62450413, ..., -0.05630391,
        -0.05630391, -0.05138463],
       ...,
       [-1.59851179,  0.55008644, -1.03304852, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -0.74630813, -0.38550655, ..., -0.05630391,
        -0.05630391, -0.05138463],
       [-0.44274597, -2.0427027 ,  0.12917322, ..., -0.05630391,
        -0.05630391, -0.05138463]])

# Support Vector Regressor

In [10]:
#Implementing Support Vector Regressor with radial basis function
svr_rbf = SVR(kernel='rbf')
svr_rbf.fit(X_train, y_train)
svr_rbf.score(X_test, y_test)

0.2063803584082815

In [11]:
#Implementing Support Vector Regressor with polynomial function
svr_poly = SVR(kernel='poly', degree=2)
svr_poly.fit(X_train, y_train)
svr_poly.score(X_test, y_test)

0.18266215211874626

In [12]:
#Implementing Support Vector Regressor with sigmoid function
svr_sg = SVR(kernel='sigmoid')
svr_sg.fit(X_train, y_train)
svr_sg.score(X_test, y_test)

0.4867409362089056

In [13]:
#Implementing Support Vector Regressor with linear function
svr_lr = SVR(kernel='linear')
svr_lr.fit(X_train, y_train)
svr_lr.score(X_test, y_test)

0.7962725308517551

# Accuracy

In [26]:
#Comparing all score
print('Radial Basis = ',svr_rbf.score(X_test, y_test).round(4))
print('Linear = ',svr_lr.score(X_test, y_test).round(4))
print('Polynomial = ',svr_poly.score(X_test, y_test).round(4))
print('Sigmoid = ',svr_sg.score(X_test, y_test).round(4))

Radial Basis =  0.2064
Linear =  0.7963
Polynomial =  0.1827
Sigmoid =  0.4867


### We got high accuracy when using linear kernel

# Predition

In [27]:
#Predition on the data with linear SVR
y_pred = svr_lr.predict(X_test)
y_pred

array([ 86.53673464,  33.70390806, 122.48356838, ...,  26.23978753,
        64.52634655, 176.17532793])

# Accuracy Evaluation

In [28]:
#Computing Root Mean Squred Error
MSE = mean_squared_error(y_test, y_pred)
RMSE = np.sqrt(MSE)
print('Mean Squred Error', MSE)
print('Root Mean Squared Error',RMSE)

Mean Squred Error 4093.4831852475745
Root Mean Squared Error 63.9803343633618
